env:
  browser: true
  es6: true
  node: true

extends:
  - eslint:recommended
  - plugin:import/recommended
  - plugin:import/react
  - plugin:react/recommended
  - prettier
  - prettier/react

root: true

settings:
  import/resolver:
    node:
      extensions:
        - .js
        - .jsx
  react:
    version: detect

rules:
  import/order:
    - error
    - alphabetize:
        order: asc
