env:
  browser: true
  es6: true
  node: true

extends:
  - eslint:recommended
  - plugin:react/recommended
  - prettier
  - prettier/react

parserOptions:
  ecmaFeatures:
    jsx: true
  sourceType: module
