version: 2.1

executors:
  node:
    parameters:
      version:
        type: string
        default: lts
    docker:
      - image: circleci/node:<< parameters.version >>
    working_directory: ~/marp

commands:
  install:
    parameters:
      postinstall:
        type: steps
        default: []
      yarn:
        type: string
        default: 1.19.1
    steps:
      - run:
          name: Upgrade yarn for current user
          command: cd ~ && yarn policies set-version << parameters.yarn >>

      - restore_cache:
          keys:
            - v2.1-dependencies-{{ .Environment.CIRCLE_JOB }}-{{ checksum "yarn.lock" }}-{{ .Branch }}
            - v2.1-dependencies-{{ .Environment.CIRCLE_JOB }}-{{ checksum "yarn.lock" }}-
            - v2.1-dependencies-{{ .Environment.CIRCLE_JOB }}-

      - run: yarn install
      - steps: << parameters.postinstall >>

      - save_cache:
          key: v2.1-dependencies-{{ .Environment.CIRCLE_JOB }}-{{ checksum "yarn.lock" }}-{{ .Branch }}
          paths:
            - node_modules
            - ~/.cache/yarn

  audit:
    steps:
      - checkout
      - install:
          postinstall:
            - run: yarn audit

  test:
    steps:
      - run: node --version

      - checkout
      - install

      - run:
          name: Prettier formatting
          command: yarn check:format

      - run:
          name: ESLint
          command: yarn lint

jobs:
  audit:
    executor: node
    steps:
      - audit

  test-node:
    executor:
      name: node
      version: '12.13.0' # Specify LTS version for development
    steps:
      - test

workflows:
  test:
    jobs:
      - audit
      - test-node:
          requires:
            - audit
